### ISSUE TITLE
味噌鐡　カギロイ - 神保町/居酒屋

### ISSUE THREAD

**Issue by tsutomu-kobayashi** [shouichi/tabelog#325]
味噌鐡　カギロイ - 神保町/居酒屋 [食べログ] https://tabelog.com/tokyo/A1310/A131003/13043691/

**Comment by shouichi** [comment]
湯島の玉響を思い出すな。

**Comment by tsutomu-kobayashi** [comment]
あーあそこ良かったなあ。また行きたい。
