### ISSUE TITLE
 蔵くら - 神田/ビアバー

### ISSUE THREAD

**Issue by tsutomu-kobayashi** [shouichi/tabelog#424]
蔵くら - 神田/ビアバー [食べログ] https://tabelog.com/tokyo/A1310/A131002/13009331/

**Comment by shouichi** [comment]
次はここだな。

**Comment by tsutomu-kobayashi** [comment]
Webサイト http://j-beer.com/index.html
ハッピーアワーもあるみたい！

**Comment by shouichi** [comment]
> 完全禁煙のきれいな空気があってこそ、ビールが生き生きと輝き始めるのです。

💯
