### ISSUE TITLE
ノムノ （nomuno） - 赤坂見附/ワインバー

### ISSUE THREAD

**Issue by tsutomu-kobayashi** [shouichi/tabelog#432]
ノムノ （nomuno） - 赤坂見附/ワインバー [食べログ] https://tabelog.com/tokyo/A1308/A130801/13222543/

けっこういいワイン飲み放題らしい。フランス人から聞いた。

**Comment by shouichi** [comment]
いくズラ 🍷

**Comment by tsutomu-kobayashi** [comment]
紹介してくれた人曰く：
Further information: it seems we have to book several weeks in advance. Considering it is times for end-of-the-year and then beginning-of-the-year parties, we should probably wait January and book it for February.

**Comment by shouichi** [comment]
ic
